//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 11:15:43 AM EEST 
//


package net.opengis.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class Snippetliteral
    extends JAXBElement<String>
{

    protected final static QName NAME = new QName("http://www.opengis.net/kml/2.2", "snippet");

    public Snippetliteral(String value) {
        super(NAME, ((Class) String.class), null, value);
    }

    public Snippetliteral() {
        super(NAME, ((Class) String.class), null, null);
    }

}
