//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 11:15:43 AM EEST 
//


package net.opengis.kml.ex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TourControlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TourControlType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.google.com/kml/ext/2.2}AbstractTourPrimitiveType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.google.com/kml/ext/2.2}playMode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TourControlType", propOrder = {
    "playMode"
})
public class TourControlType
    extends AbstractTourPrimitiveType
{

    @XmlElement(defaultValue = "pause")
    protected PlayModeEnumType playMode;

    /**
     * Gets the value of the playMode property.
     * 
     * @return
     *     possible object is
     *     {@link PlayModeEnumType }
     *     
     */
    public PlayModeEnumType getPlayMode() {
        return playMode;
    }

    /**
     * Sets the value of the playMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayModeEnumType }
     *     
     */
    public void setPlayMode(PlayModeEnumType value) {
        this.playMode = value;
    }

}
